version: '3.1'
services:
  RevProxy:
    image: haproxytech/haproxy-alpine:latest
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
      - "85:85"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      whiskers-net:
        ipv4_address: 172.28.0.2

  webapp:
    build:
      context: ../WhiskersWebApp
      dockerfile: ../WhiskersWebApp/Dockerfile
    env_file:
      - .env
    ports:
      - "3010:3000"
    networks:
      whiskers-net:
        ipv4_address: 172.28.0.3

  webapp1:
    build:
      context: ./../WhiskersWebApp
      dockerfile: ./../WhiskersWebApp/Dockerfile
    env_file:
      - .env
    ports:
      - "3011:3000"
    networks:
      whiskers-net:
        ipv4_address: 172.28.0.4


  api:
    build:
      context: ./../Whiskers_API
      dockerfile: ./../Whiskers_API/Dockerfile
    restart: always
    ports:
      - "3020:3000"
    env_file:
        - .env
    networks:
      whiskers-net:
        ipv4_address: 172.28.0.5

  GameServer:
    image: node:latest
    restart: always
    ports:
      - "3030:3000"
    env_file:
        - .env
    volumes:
        - ./../Redwhiskers_Sockets:/usr/src/app
    networks:
      whiskers-net:
        ipv4_address: 172.28.0.7

  AI:
    image: python:latest
    restart: always
    ports:
      - "3040:3000"
    env_file:
      - .env
    volumes:
      - ./../red-whiskers-AI:/usr/src/app
    networks:
      whiskers-net:
        ipv4_address: 172.28.0.9


  DB:
    image: mongo:latest
    restart: always
    ports:
      - "21017:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USR}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PWD}
      MONGO_INITDB_DATABASE: whiskers
    volumes:
      - dbdata6:/data/db
    networks:
      whiskers-net:
        ipv4_address: 172.28.0.11

volumes:
  dbdata6:

networks:
  whiskers-net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.28.0.0/24"
